# Generated by Django 5.2.4 on 2025-08-06 14:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirePerimeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('agency', models.CharField(max_length=3)),
                ('unit_id', models.CharField(max_length=3)),
                ('fire_name', models.CharField(max_length=34)),
                ('inc_num', models.CharField(max_length=8)),
                ('alarm_date', models.DateField()),
                ('cont_date', models.DateField()),
                ('cause', models.IntegerField()),
                ('c_method', models.IntegerField()),
                ('objective', models.IntegerField()),
                ('gis_acres', models.FloatField()),
                ('comments', models.CharField(max_length=100)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
    ]
