# Generated by Django 5.2.4 on 2025-08-11 12:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_alter_fireperimeter_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostfireDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.CharField(blank=True, max_length=50)),
                ('streetnumb', models.BigIntegerField(blank=True, null=True)),
                ('streetname', models.CharField(blank=True, max_length=50)),
                ('streettype', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.BigIntegerField(blank=True, null=True)),
                ('calfireuni', models.CharField(blank=True, max_length=3)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('incidentna', models.CharField(blank=True, max_length=20)),
                ('incidentnu', models.CharField(blank=True, max_length=20)),
                ('incidentst', models.DateField(blank=True, null=True)),
                ('hazardtype', models.CharField(blank=True, max_length=20)),
                ('defensivea', models.CharField(blank=True, max_length=50)),
                ('structuret', models.CharField(blank=True, max_length=254)),
                ('structurec', models.CharField(blank=True, max_length=100)),
                ('exteriorsi', models.CharField(blank=True, max_length=50)),
                ('yearbuilt', models.BigIntegerField(blank=True, null=True)),
                ('siteaddres', models.CharField(blank=True, max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
