# Generated by Django 5.2.4 on 2025-08-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_postfiredamage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiredamage',
            name='defensivea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
