# Generated by Django 5.2.4 on 2025-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_alter_postfiredamage_defensivea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiredamage',
            name='calfireuni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='damage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='defensivea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='exteriorsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='hazardtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='incidentna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='incidentnu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='siteaddres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='streetname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='streetnumb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='streettype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='structurec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='structuret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='yearbuilt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postfiredamage',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
